### PR TITLE
Improve stringify() and parse() + full support of backslash

### PR DESCRIPTION
**Pull request by A-312**
- Fix error/oversight: backslash was not escaped. fix: #14, fix: #16
 - Property name is scoped in `["..."]` only with special char (other than A-z0-9_) or is started with a number.

# Before : 
```js
// JSON.stringify:
dico = {
  "a\"": 0,
  "a\\\"": 1,
  "a\\\\\"": 2,
  "end": true
}
// ObjectPath.stringify&parse:
a" path : ["a\""] is good
a\" path : ["a\\""] is wrong expected: a\\\" got: a\\"
a\\" path : ["a\\\""] is wrong expected: a\\\\\" got: a\\\"
```

# After (with this PR) : 
```js
// JSON.stringify:
dico = {
  "a\"": 0,
  "a\\\"": 1,
  "a\\\\\"": 2,
  "end": true
}
// ObjectPath.stringify&parse:
a" path : ["a\""] is good
a\" path : ["a\\\""] is good
a\\" path : ["a\\\\\""] is good
```
<details>
  <summary>Test script</summary>
  
```javascript
const parse = require('./').parse
const stringify = require('./').stringify

const list = [
  'a"',
  'a\\"',
  'a\\\\\"'
]

// vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// v v v v v v v v OUTPUT SCRIPTS FOR TESTS v v v v v v v v
//  v v v v v v v  OUTPUT SCRIPTS FOR TESTS  v v v v v v v 
// v v v v v v v v OUTPUT SCRIPTS FOR TESTS v v v v v v v v
// vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

const expected = (() => {
  const dico = {}

  list.forEach((prop, index) => {
    dico[prop] = index
  });
  dico.end = true

  return JSON.stringify(dico, null, 2)
})()

console.log("dico =", expected)

list.forEach((before, index) => {
  after = stringify(parse(before), '"')
  console.log(before, "path :", after, "is", testPath(after, index))
})

function testPath(path, index) {
  // Regex test: Should be the same value of JSON.stringify output
  const name = path.replace(/^\["(.*)"\]$/, '$1')
  if (!expected.includes(`\n  "${name}": ${index},`)) {
    return "wrong expected: " + expected.match(new RegExp(`\\n  "(.+)"\: ${index},\\n`))[1] + " got: " + name;
  }

  //  ECMAScript test (with eval): Should not throw
  try {
    eval(path)
    return "good"
  } catch (e) {
    if (e.message.indexOf("Cannot read property") !== -1)
      return "good"
    else
      return "wrong with ES"
  }
}
```
  
</details>

### CODE REVIEW

**Comment by A-312** [comment]
This PR is not ready

**Comment by A-312** [comment]
@mike-marcacci My PR is ready. Now, the backslash will have the same behavior of `JSON.stringify`, let see this test: https://github.com/mike-marcacci/objectpath/pull/15/commits/c1ba01233a10d13c3785ea728bf0b505f26b2efc#diff-910eb6f57886ca16c136101fb1699231R135

**Comment by A-312** [comment]
@mike-marcacci this one is ready

**Comment by mike-marcacci** [comment]
Your improvements here are excellent, especially with more human-friendly outputs. I'd like to release this with a new major, since the output of `normalize` has changed in format. Is this OK with you?

On a totally separate note, looking over this codebase to review your changes has brought to my attention some unnecessary time complexity in parts of my original algorithm. I haven't heard any complaints so far, but perhaps at some point I will refactor this.

**Comment by mike-marcacci** [comment]
And thank so much for the great contribution!

**Comment by A-312** [comment]
Yes, it is Ok for me. I made breakchange on backslash behavior even I fix a bug.

And on the output is not the same (human-friendly is by default, and the old output can be force woth forceQuote).

**Comment by A-312** [comment]
I forgot to update readme about human friendly key @mike-maracci

**Pull request merged**
